<?php
// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/conf/github.auth';

$client = new \Github\Client();
$client->authenticate($token,$pass,Github\Client::AUTH_URL_TOKEN);

function list_repos($client) {
    //Do some request
    $repositories = $client->api('organization');

    $paginator = new Github\ResultPager($client);
    $parameters = array('gsb-public');
    $repos = $paginator->fetchAll($repositories, 'repositories', $parameters);
    return $repos;
}

function watch_repos($client, $repos) {
    foreach ($repos as $repo) {
        echo $client->api('current_user')->watchers()->watch('gsb-public', $repo['name']);
    }
}

function get_branch($client) {
    $repos = list_repos($client);
    foreach($repos as $key => $repo) {
        try {
            $hasBranch = $client->api('repo')->branches('gsb-public', $repo['name'], 'WP-8109');
            if ($hasBranch) {
                print 'cd /var/www/gsb-build-local/src/gsb_public/profiles/gsb_public/modules/custom/features/'.$repo['name']."\n";
                print "git fetch\n";
                print "git diff origin/WP-8109\n";
                print "git checkout *\n";
            }
        } catch (Exception $e) {
            //echo 'Caught exception: ', $e->getMessage(), "\n";
        }
    }
}

print_r(get_branch($client));
